# Generated by Django 3.2.6 on 2022-05-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='filter_name',
            new_name='first_name',
        ),
    ]
